### ISSUE TITLE
Fast Subdivision doesn't apply to the undo history

### ISSUE THREAD

**Issue by SenhorPatolino** [ArmoredColony/ARMORED-Toolkit#4]
A regular subdivision using CTRL + [1, 2..] is registered to the undo history, fast subdivision does not though
![image](https://github.com/ArmoredColony/ARMORED-Toolkit/assets/61413244/0a17ce6c-90d8-48ed-aeb9-73a33a53be5c)

Just reporting cause its something that took me a bit of time until I figured out it was the addon and not Blender being quirky 😅

**Comment by ArmoredColony** [comment]
I did that intentionally but this video shows how you can change it:

https://github.com/ArmoredColony/ARMORED-Toolkit/assets/78882317/79fb6aca-b69a-4abf-98be-facb2839b69d

This is the text you can add to the script so it works the way you want:
'UNDO'

**Comment by SenhorPatolino** [comment]
Appreciate it!
